In [0]:
import numpy as np

In [3]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

In [5]:
a = np.array([10, 30, 20, 4,30, 51, 7, 2, 4, 40, 100])
a[4]

30

In [6]:
# Mostrar valores desde el indice 3 en adelante
a[3:]

array([  4,  30,  51,   7,   2,   4,  40, 100])

In [7]:
#Imprimir el arreglo a traves de intervalos, de la posicion 3 a la 7
a[3:7]

array([ 4, 30, 51,  7])

In [8]:
#posicion de inicio y cada cuanto quiero saltar el indice
a[1::4]

array([30, 51, 40])

In [9]:
#Cinco elemento en el valor de array de ceros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [0]:
# Matriz de 1 de 4 x 5
ones = np.ones((4,5))

In [18]:
type(ones)

numpy.ndarray

In [20]:
type(ones[3,4])

numpy.float64

In [16]:
# crear un arreglo de elementos primer parametro, parametro final,
# y cuentos elementos queremos entre esos dos de forma
# equidistante
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [21]:
# crear array de dos dimensiones
b = np.array([['x','y','z'],['a','c','e']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [22]:
#numero de dimensiones
b.ndim

2

In [23]:
# ordenar de menor a mayor
c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [24]:
# nombre es string de 10 elementos y edad tipo int
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15)]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [25]:
# llenar arreglos de forma dinamica con arange
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
# arreglo con limite inferior y superior
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
# arraglo con incremento de 5 con comiezo y final
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
#Arrglo bidimensional y que contenga solo un valor
np.full((3, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [30]:
# metodo util con matrices para generar una diagonal con numeros indicados
np.diag([0, 3, 9, 10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

In [31]:
# nombre es string de 10 elementos y edad tipo int
cabeceras = [('nombre', 'S10'), ('edad', int), ('pais', 'S15')]
datos = [('Juan', 10, 'Brasil'), ('Maria', 70, 'Colombia'), 
         ('Javier', 42, 'Peru'), ('Samuel', 15, 'Italia')]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'pais')

array([(b'Juan', 10, b'Brasil'), (b'Maria', 70, b'Colombia'),
       (b'Samuel', 15, b'Italia'), (b'Javier', 42, b'Peru')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('pais', 'S15')])

In [35]:
# nombre es string de 10 elementos y edad tipo int
cabeceras = [('nombre', 'S10'), ('edad', int), ('pais', 'S15')]
datos = [('Juan', 10, 'Brasil'), ('Maria', 70, 'Colombia'), 
         ('Javier', 42, 'Peru'), ('Samuel', 70, 'Italia')]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = ('edad','pais'))

array([(b'Juan', 10, b'Brasil'), (b'Javier', 42, b'Peru'),
       (b'Maria', 70, b'Colombia'), (b'Samuel', 70, b'Italia')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('pais', 'S15')])